### ISSUE TITLE
[Question]: Running Unit Test cases 

### ISSUE THREAD

**Issue by naftalimurgor** [metaplex-foundation/metaplex-program-library#1012]
### Which package is this feature request for?

token-metadata

## Description
Scenario: Running Tests (without) deploying programs. Say,I wan to run quick tests for `token-metadata/` without having to deploy the programs to devnet/Local cluster. I can't seem to figure out how to do it correctly and sesems also can't find appropriate documentation for running an individual test.

Thanks

### Standard Change?

No

### Ideal solution or implementation

N/A

### Alternative solutions or implementations

Is it possible to run isolated tests. i.e indivdiual test for a given program?

### Other context

N/A

**Comment by febo** [comment]
The [Programmable NFT Guide](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/token-metadata/program/ProgrammableNFTGuide.md) includes instructions on how to setup your local environment to run tests (last section of the document).
