### ISSUE TITLE
[Bug]:  sized collection counts

### ISSUE THREAD

**Issue by dtmrc** [metaplex-foundation/metaplex-program-library#1023]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

reproduce (using the collection.metaplex.com tool):
1. create a `sized-collection A`
2. attach tokens with `first-creator A`
3. attach tokens with `first-creator B`
4. `sized-collection A` collectionDetails.size should be `first-creator A` length + `first-creator B` length
5. create a `collection B`
6. attach tokens with `first-creator B`
7. migration of `collection B` to sized collection should fail
8. however, tokens with `first-creator B` are now associated to `collection B`
9. remove  tokens with `first-creator B` using `UnverifySizedCollectionItem` (using js sdk client)
* **the onchain value of `sized-collection A` size is now off**
    * i've run into an issue where my collection size count is incorrect, by following the steps above. now the `sized-collection A` size should be the length of tokens with `first-creator A`.

### Priority this issue should have

Low (slightly annoying)

**Comment by samuelvanderwaal** [comment]
> i've run into an issue where my collection size count is incorrect, by following the steps above. now the sized-collection A size should be the length of tokens with first-creator A.

What does the size end up being instead?
