### ISSUE TITLE
[Bug]: Bubblegum Decompression does not work for verified Collection NFTs

### ISSUE THREAD

**Issue by ethyi** [metaplex-foundation/metaplex-program-library#1070]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

1. Mint a standard collection with master edition with your wallet
2. Create a merkle tree through bubblegum with your wallet
3. Mint a compressed NFT with the MintToCollection instruction on bubblegum with the same collection and tree (must specify {verified:false] and the ixn will automatically verify the collection if collection auth matches signer)
4. Attempt to decompress NFT into the same metadata {verified:true}
You will observe that the txn fails, with error "Cannot verify collection in this ixn"

### Priority this issue should have

High (immediate attention needed)

**Comment by danenbm** [comment]
Getting fixed in https://github.com/metaplex-foundation/metaplex-program-library/pull/1087

**Comment by danenbm** [comment]
With the recent patch fix to Token Metadata ( v1.11.2 on May 26, 2023), compressed NFTs can also now be decompressed with with collection set to verified.
