### ISSUE TITLE
[Bug]: Borsch Serialization Error; V1 Data No Longer Working

### ISSUE THREAD

**Issue by joshwolff1** [metaplex-foundation/metaplex-program-library#1088]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

Creating a metadata account with the DataV1 results in a Borsch serialization error. This error began last night after the metadata contract update.

### Relevant log output

```shell
'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]',
'Program log: Error: BorshIoError',
'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 4273 of 1197033 compute units',
'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Failed to serialize or deserialize account data: Unknown'
```

### Priority this issue should have

High (immediate attention needed)

**Comment by joshwolff1** [comment]
You can also reproduce this with Metaboss. Example:

metaboss mint one --keypair keys/solana-keypair.json --nft-data-file example_nft_data.json --receiver APipLFSda8yjUaSMk69m8yA1KT6RE5MR1Ltso4ciirzW --immutable --primary-sale-happened

**Comment by samuelvanderwaal** [comment]
> You can also reproduce this with Metaboss. Example:
> 
> metaboss mint one --keypair keys/solana-keypair.json --nft-data-file example_nft_data.json --receiver APipLFSda8yjUaSMk69m8yA1KT6RE5MR1Ltso4ciirzW --immutable --primary-sale-happened

What version of Metaboss are you using?

```
metaboss -V
```

**Comment by samuelvanderwaal** [comment]
`create_metadata_account` and `create_metadata_accounts_v2` have been deprecated to free up binary space: https://twitter.com/nhanvp/status/1653886053634416641?s=20

You can mint new NFTs with the legacy handler `create_metadata_accounts_v3` or the new unified handlers `create` and `mint`. Metaboss was updated a while back not to use `create_metadata_account_v2` so you're probably just running an older version of it.

**Comment by joshwolff1** [comment]
Thank you for that! I really appreciate it. Turns out I was using an old instruction, both in my code and the metaboss version.
