### ISSUE TITLE
[Bug]: mpl-token-metadata v1.12.0 function `cmp_pubkeys` is private

### ISSUE THREAD

**Issue by D0bhareach** [metaplex-foundation/metaplex-program-library#1118]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

Add dependency to Anchor project with: `mpl-token-metadata = {version = "=1.12.0", features = ["no-entrypoint"]}`   
Cargo check failed with  log.

### Relevant log output

```shell
Checking mpl-token-metadata v1.12.0
error[E0603]: function `cmp_pubkeys` is private
  --> /bla-bla/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mpl-token-metadata-1.12.0/src/processor/metadata/transfer.rs:3:38
   |
3  | use mpl_token_auth_rules::processor::cmp_pubkeys;
   |                                      ^^^^^^^^^^^ private function
   |
note: the function `cmp_pubkeys` is defined here
  --> /bla-bla/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mpl-token-auth-rules-1.4.0/src/processor/mod.rs:22:5
   |
22 |     utils::cmp_pubkeys,
   |     ^^^^^^^^^^^^^^^^^^
```

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
This should be fixed now. You may need to run `cargo clean` and rebuild or `cargo update`.
