### ISSUE TITLE
[Feature]: Unpin Solana Client Version

### ISSUE THREAD

**Issue by jacobcreech** [metaplex-foundation/metaplex-program-library#1136]
### Which package is this feature request for?

bubblegum

### Feature

Bubblegum currently has the Solana client version pinned to 1.14.13 - is there a reason for this or can we relax it?

https://github.com/metaplex-foundation/metaplex-program-library/blob/d6f96f67b187104e6c4622b99f466bc530fc2b7d/bubblegum/program/Cargo.toml#L26

### Standard Change?

No

### Ideal solution or implementation

Unpin if possible

**Comment by samuelvanderwaal** [comment]
I think it could be relaxed to a patch dependency: `"~1.14"` so it would pull in up to `1.14.17`. Bubblegum doesn't work currently with Solana 1.16's breaking changes so going more loose than a patch dependency doesn't make sense IMO.

**Comment by samuelvanderwaal** [comment]
This was relaxed to the "patch pin" in the latest release. I think that's the best we can do atm.
