### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by KirillLykov** [metaplex-foundation/metaplex-program-library#1137]
### Which package is this feature request for?

auction-house

### Feature

Problem: while investigating recent issue https://github.com/solana-labs/solana/issues/31960, I found out that metaplex repository consists of several independent rust workspaces each having it's own versions of dependencies. Beside of using different versions of third-party dependencies, some programs use specific version of programs from the same repo which creates conflicts

### Standard Change?

No

### Ideal solution or implementation

Why not make one workspace with all the dependencies versions defined on the root-level Cargo.toml file.

**Comment by samuelvanderwaal** [comment]
The programs in MPL were never as tightly coupled as Solana's monorepo and have been released with independent versions and various dependencies. Keeping them as a single workspace was a nightmare and so we removed it as a path to breaking up the monorepo. There's no good reason Auction House should be in the same workspace as Token Metadata, IMO.

If there are specific dependency issues with Auction House let me know and we can work to resolve them.

**Comment by KirillLykov** [comment]
The problem is that we MPL will migrate to solana 1.16.2, it looks like it is required to migrate to borsh 0.10.3 and anchor 0.28. If one program uses another one not from the latest version, it might be a problem because they may use different serialization/deserialization procedures. Not sure if this serialization/de-serialization is a the real problem but [this issue](https://github.com/solana-labs/solana/issues/31960) suggests that it might be.

**Comment by samuelvanderwaal** [comment]
> The problem is that when MPL will migrate to solana 1.16.2, it looks like it is required to migrate to borsh 0.10.3 and anchor 0.28. If one program uses another one not from the latest version, it might be a problem because they may use different serialization/deserialization procedures. Not sure if this serialization/de-serialization is a the real problem but [this issue](https://github.com/solana-labs/solana/issues/31960) suggests that it might be.

Yeah, I think borsh serialization is the issue preventing us from upgrading to Solana v1.16 at this point, but I haven't done a thorough analysis yet. I expect us to upgrade before 1.16 actually goes to mainnet but not sure when exactly yet.

**Comment by samuelvanderwaal** [comment]
Closing because we are in-fact breaking up the mono-repo. Token Metadata specifically is being moved [here](https://github.com/metaplex-foundation/mpl-token-metadata).
