### ISSUE TITLE
How can I update maxSupply in data of MasterEdition?

### ISSUE THREAD

**Issue by blockchainlover2019** [metaplex-foundation/metaplex-program-library#196]
I want to extend maxSupply of Editions.
but I can't find any rust instruction for this solution.
How can I do this?
Please help me!

**Comment by basvanberckel** [comment]
The max supply is (I would assume) intentionally immutable. You cannot update this after creation.

**Comment by ppoliani** [comment]
How does immutability in this scenario differs from the immutability of the metadata itself. You can mutate metadata already so wouldn't it make sense to be able to mutate the max supply value, as well?
