### ISSUE TITLE
redeem_printing_v2_bid fails with on-chain collections

### ISSUE THREAD

**Issue by basvanberckel** [metaplex-foundation/metaplex-program-library#224]
redeem_printing_v2_bid always throws an error when called for a MasterEdition with an on-chain collection.

The error occurs when the new edition is minted, through the following calls:

- process_redeem_printing_v2_bid
- mint_edition
- process_mint_new_edition_from_master_edition_via_vault_proxy
- process_mint_new_edition_from_master_edition_via_token_logic
- mint_limited_edition
- process_create_metadata_accounts_logic
- assert_collection_update_is_valid

Where the CollectionCannotBeVerifiedInThisInstruction error is thrown

This happens because the collection of the MasterEdition is already verified, which transfers over to the newly minted edition, but the assert_collection_update_is_valid function doesn't allow a collection to already be verified.

The assert_collection_update_is_valid function should be updated to check if there is an existing (this param already exists) entry which is already verified.

Then process_create_metadata_accounts_logic should be updated to receive the old metadata and pass this to assert_collection_update_is_valid.

**Comment by yamijuan** [comment]
Already fixed afaik
