### ISSUE TITLE
[Feature]: CandyMachine: Allow endSettings to respect Date and Amount at same time, whichever is sooner

### ISSUE THREAD

**Issue by dborstelmann** [metaplex-foundation/metaplex-program-library#287]
### Which package is this feature request for?

candy-machine

### Feature

Today, endSettings only respects amount or date.  We would like both.  If amount sells out, then CM stops minting ability.  But if a date is hit before it sells out, CM also stops minting ability.

### Standard Change?

No

### Ideal solution or implementation

Enable passing amount and date to endSettings

**Comment by febo** [comment]
@dborstelmann I am closing this since this is already implemented in Candy Machine V3.
