### ISSUE TITLE
[Bug]: Two issues with the fixed price sale pieces in one wallet feature

### ISSUE THREAD

**Issue by robbierogers** [metaplex-foundation/metaplex-program-library#399]
### Which package is this bug report for?

fixed-price-sale

#### It's not possible to change a market to remove a limit.

1. Create a market with pieces in one wallet set to 1
2. Suspend the market
3. Should be able to change the market pieces in one wallet to null (i.e. remove the limit)

https://github.com/metaplex-foundation/metaplex-program-library/blob/master/fixed-price-sale/program/src/processor/change_market.rs#L61-L64

#### The limit is not enforced if the wallet has more than the pieces in one wallet.

1. Create a market with pieces in one wallet set to 1
2. Should not be able to buy using a wallet that already has more than 1

https://github.com/metaplex-foundation/metaplex-program-library/blob/master/fixed-price-sale/program/src/processor/buy.rs#L75-L80

Potential fix: `if trade_history.already_bought >= pieces_in_one_wallet {`

### Priority this issue should have

Medium (should be fixed soon)

**Comment by VadimGrozinok** [comment]
Hey!
Yes, you are right
Nice catch, thank you a lot
Will work on the fix soon

**Comment by bezrazli4n0** [comment]
Hello, thanks for good observation. Fixed in #408.
