### ISSUE TITLE
[Bug]: Suspected bug in Auction house `ExecuteSale` instruction

### ISSUE THREAD

**Issue by nibbus0x** [metaplex-foundation/metaplex-program-library#431]
Someone please correct me if I'm wrong, but I believe that [this line](https://github.com/metaplex-foundation/metaplex-program-library/blob/ab9093b010a596ccf34bb4cf5226eee3dbf02b41/auction-house/program/src/lib.rs#L710) in the processing of the `ExecuteSale` instruction in the Auction House program will always fail, i.e. return Error `NumericalOverflow`.

From looking through the code, specifically the [`rent_checked_sub`](https://github.com/metaplex-foundation/metaplex-program-library/blob/d370efbd47435c6256b1f703f9bf435749d9eb5f/auction-house/program/src/utils.rs#L561) function, it seems the value of `diff` will always be less than or equal to `buyer_price`. Since this line is only executed when the 2 values are not equal this means that `buyer_price > diff`, and `checked_sub` will fail.

I believe the line is meant to read as `buyer_price.checked_sub(diff)`.

**Comment by blockiosaurus** [comment]
Ah you're correct. This is an awesome catch, thank you!

**Comment by nibbus0x** [comment]
Nw. Should I make a pr to fix, or will it be updated in the next patch/release?

**Comment by blockiosaurus** [comment]
I fixed it here (https://github.com/metaplex-foundation/metaplex-program-library/commit/e953dd73632dac34e9bf49ed42e94bd442ea4cba) since the rent-change feature is due to be switched on for mainnet any day now.

**Comment by nibbus0x** [comment]
Ok, great. Thx.
