### ISSUE TITLE
[Feature]: Allow Setting TokenStandard for Tokens Without Them

### ISSUE THREAD

**Issue by samuelvanderwaal** [metaplex-foundation/metaplex-program-library#433]
### Which package is this feature request for?

token-metadata

### Feature

Currently, when a new metadata account is created there is [logic that checks the token type](https://github.com/metaplex-foundation/metaplex-program-library/blob/e4dec2c51615ac703cbe28398646527e385346b5/token-metadata/program/src/utils.rs#L921) it is and automatically sets the TokenStandard to `Fungible`, `FungibleAsset` or `NonFungibleEdition`. The `create_master_edition`[ handler](https://github.com/metaplex-foundation/metaplex-program-library/blob/e4dec2c51615ac703cbe28398646527e385346b5/token-metadata/program/src/processor.rs#L501) is used to set it to `NonFungible` when it is called but there's no way tokens existing prior to these `token-metadata` changes to set the TokenStandard.

We need to add a new handler or handlers to do this.

### Standard Change?

No

### Ideal solution or implementation

Requirements:

* We want to set the TokenStandard based on the actual token type not an arbitrary value passed in by the user so we need to check things like if it has a master edition, edition, what the token decimals are, what the supply is, etc.

* Each new handler should have Rust tests that check expected success and failure behaviors

* If it makes sense we can consider extracting the token check logic into a separate function and using it for `process_create_metadata_accounts_logic` as well

Token Standard Types:

NonFungible: This is our standard NFT, a token account with a supply of 1, decimals 0, and a master edition PDA

NonFungibleEdition: This is our standard Edition NFT, a token account with a supply of 1, decimals 0 and an edition PDA

FungibleAsset: This is a token mint that can have a supply greater than 1 but for which decimals are 0 and which the JSON supports richer metadata

Fungible: This is a standard fungible token with basic metadata, supply can be greater than 1, decimals can be greater than 0 and basic JSON metadata.

**Comment by stranzhay** [comment]
closing covered in @samuelvanderwaal 1.3.0 changes
