### ISSUE TITLE
Remove unnecessary MustBeOneOfCreators Error in create_metadata_accounts

### ISSUE THREAD

**Issue by samuelvanderwaal** [metaplex-foundation/metaplex-program-library#439]
Currently, to create a new metadata account with `create_metadata_accounts` the update authority must be in the creator's array or else the client gets the error `MustBeOneOfCreators` triggered by [this line](https://github.com/metaplex-foundation/metaplex-program-library/blob/e4dec2c51615ac703cbe28398646527e385346b5/token-metadata/program/src/utils.rs#L121-L123). This error is unnecessary and doesn't do any good as there is no good reason that an update authority should have to be in the creator's array and a client can simply run `update_metadata_accounts_v2` and remove the update authority from the creators array after the metadata is created, negating the check anyway. 

The logic in this function is somewhat convoluted so this change needs to be done very carefully and with extra tests added as appropriate.

**Comment by roederw** [comment]
@bhgames
