### ISSUE TITLE
[Bug]: Refactor change in Auction-House breaking backward compatibility

### ISSUE THREAD

**Issue by RustySol** [metaplex-foundation/metaplex-program-library#474]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

Due to the change at
https://github.com/metaplex-foundation/metaplex-program-library/commit/facd7cb11903bab086165e6619bbf0cc6e28c272#diff-496d87d01dcc602c98aab6d398dac408faa954ffc99ce91c1ae12d5f8efc2782R18

The originally working code is now emitting `Error Message: A mut constraint was violated` messages.
How I identified is by removing the line and rebuild in local and then the call went through again!

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
Thanks for the report, I'm working on this now.
