### ISSUE TITLE
[Bug]: get_supply_off_master_edition() error with offsets

### ISSUE THREAD

**Issue by flashleforshort** [metaplex-foundation/metaplex-program-library#486]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

The MasterEdition structs don't store `supply` as an `Option<u64>` as assumed in `get_supply_off_master_edition()` and `get_max_supply_off_master_edition()` in the `utils.rs` module within the token_metadata program. This messes up with how EditionMarker PDAs are derived, specially in the fixed price sale program, that's where I encountered this problem.

This can be easily fixed by just changing the offsets accordingly.

### Priority this issue should have

Medium (should be fixed soon)

**Comment by flashleforshort** [comment]
#487 This pull request should fix the offsets

**Comment by roederw** [comment]
`supply` should NOT be an Option.

**Comment by roederw** [comment]
This is a breaking change for current stored data layout. Closing.

**Comment by flashleforshort** [comment]
I think you misread, the functions I mention read the byte representation as if it were an option, AND IT IS NOT. I believe this is a BUG in Metaplex's code. I'M NOT PROPOSING A CHANGE.
