### ISSUE TITLE
"Program did not complete" error when CPI-ing into Metaplex contracts

### ISSUE THREAD

**Issue by Reyth3** [metaplex-foundation/metaplex-program-library#516]
Hi, 

We are building our project on top of the Metaplex library. We're trying to build a collection programatically from our contract and we got it to work technically, but the problem is it only works once every few times we run the JS tests. Sometimes it passes just fine, but often it just throws a "Program could not complete" error and there's no indication whatsoever as to why that's the case. It seems to be happening mostly when trying to call `mpl_token_metadata`, but I have no way to confirm that. It happens during the transaction simulation stage, so we don't even get any logs related to the issue.

Has anyone else had a similar issue? What can I do when my problem sometimes doesn't complete seemingly withouta good reason?

**Comment by roederw** [comment]
Can you provide a Transaction we could look at?
