### ISSUE TITLE
[Bug]: the code is contradictory

### ISSUE THREAD

**Issue by Tonyce** [metaplex-foundation/metaplex-program-library#552]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

https://github.com/metaplex-foundation/metaplex-program-library/blob/master/token-metadata/program/src/processor.rs#L1476-L1490

### Priority this issue should have

Low (slightly annoying)

**Comment by samuelvanderwaal** [comment]
You are correct; thanks for the callout.

**Comment by Tonyce** [comment]
the some superfluous and contradictory code also in other files
