### ISSUE TITLE
[Bug]: Trade state account not close after the sale is executed

### ISSUE THREAD

**Issue by rm1138** [metaplex-foundation/metaplex-program-library#575]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

**devnet**
1. Create a seller trade state
2. Create a buyer trade state
3. Execute the sale
4. Both trade state accounts still exist

### Relevant log output

[Transaction log](https://explorer.solana.com/tx/2gMakQ5xVt2AnJbWNpsohxTVDU5Xm51h9n1b1zZqrtJQXL4kXgPYFt1qnapxE3Lwsv9vYf8HT7KTSNLL2q1Rs5Ck?cluster=devnet)

### Priority this issue should have

Medium (should be fixed soon)

**Comment by rm1138** [comment]
Any update? I saw this behavior also appear on mainnet-beta. Is this a bug or a behavior change?

**Comment by boredjoker** [comment]
anything new?

**Comment by samuelvanderwaal** [comment]
> anything new?

This should be fixed as of December. Is it still happening?
