### ISSUE TITLE
[Feature]: burn_nft for old tokens

### ISSUE THREAD

**Issue by Flawm** [metaplex-foundation/metaplex-program-library#620]
### Which package is this feature request for?

token-metadata

### Feature

I have many tokens (thousands) that have no master edition account that could be burned / closed for gas, however the burn_nft function requires master edition. These tokens were minted before the metaplex standard was solidified and/or leveraging master edition accounts to do freezes & such.

Unfortunately, I can't retroactively add master edition info like SMB did, as the mint authority is nulled out and I can't otherwise work the metadata program.

### Standard Change?

No

### Ideal solution or implementation

`process_burn_nft` does a check on the mint's mint authority, if it's None it can skip closing & checking the master edition account

### Other context

this would make me very happy :)

**Comment by samuelvanderwaal** [comment]
> ### Which package is this feature request for?
> 
> token-metadata
> ### Feature
> 
> I have many tokens (thousands) that have no master edition account that could be burned / closed for gas, however the burn_nft function requires master edition. These tokens were minted before the metaplex standard was solidified and/or leveraging master edition accounts to do freezes & such.

Do you mean you have thousands of *different* tokens, each with their own metadata account, or do you mean you have thousands of a single toke type?

We have a [burn print edition](https://github.com/metaplex-foundation/metaplex-program-library/discussions/689) feature in progress and I'd like to consider burning solo metadata accounts as well, though I think it should be a separate handler.

**Comment by Flawm** [comment]
The former, thousands of tokens with a nulled mint authority and no master edition account, and unlike SMB I don't have dick swing to use metadata program to fix stuff. Would be greatly appreciated
