### ISSUE TITLE
[Bug]: Add remaining accounts to Auction House execute sale JS lib

### ISSUE THREAD

**Issue by 0xPratik** [metaplex-foundation/metaplex-program-library#678]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

JS SDK

### Issue description

I want to add remaining accounts to the execute sale function using the low level SDK but haven't found how can i go that.

### Priority this issue should have

Low (slightly annoying)

**Comment by 0xPratik** [comment]
@thlorenz This is related to Solita i think

**Comment by thlorenz** [comment]
Hi thanks for the report. Could you please provide an example of what you're trying to do? I'm assuming you're referring to [this instruction](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/auction-house/js/src/generated/instructions/executeSale.ts#L100).

I looked into the [IDL genrated by anchor](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/auction-house/js/idl/auction_house.json#L931) and don't see any indicator in there of _remaining accounts_ that solita could pick up on to generate the correct code.

If I understand correctly then anchor has a notion of _implicit_ remaining accounts on the `Context` object?

```
/// Remaining accounts given but not deserialized or validated.
/// Be very careful when using this directly.
pub remaining_accounts: &'c [AccountInfo<'info>],
```

Would that mean that for each instruction their could potentially be _remaining accounts_ required even if that is not included in the IDL info? If so we should add a feature to solita to optionally provide those accounts.


If the above makes sense then let's continue discussion in the solita repo in a separate issue to work out what the generated code would look like and how it'd be used. We have to come up with a good solution if as I mentioned above potentially any instruction could have implicit _remaining accounts_ and thus those changes would affect each and every instruction rendered by solita.

**Comment by 0xPratik** [comment]
Yes you are correct its like optional accounts. all the deserialization of the remaining accounts takes place in the business logic of the program itself. In the case of executeSale instruction, it takes in the creator's address for royalty distribution without remaining accounts this instruction wont work

**Comment by thlorenz** [comment]
Thought about how to solve this and since there is no way for solita to know which accounts need to be _writable_ and such the user would have to provide that info. Thus updating the solita generated code for (as an example) _executeSale_ could look like this:

```ts
export type ExecuteSaleInstructionAccounts = {
  buyer: web3.PublicKey
  seller: web3.PublicKey
  tokenAccount: web3.PublicKey
  tokenMint: web3.PublicKey
  [ .. many more .. ]
  programAsSigner: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

[ .. ]

export function createExecuteSaleInstruction(
  accounts: ExecuteSaleInstructionAccounts,
  args: ExecuteSaleInstructionArgs,
  programId = new web3.PublicKey('hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk')
) {
  const [data] = executeSaleStruct.serialize({
    instructionDiscriminator: executeSaleInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.buyer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.seller,
      isWritable: true,
      isSigner: false,
    },
   [ .. many more .. ]
  }

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix

```

Where AccountMeta is the following type:

```ts
  export type AccountMeta = {
    /** An account's public key */
    pubkey: PublicKey;
    /** True if an instruction requires a transaction signature matching `pubkey` */
    isSigner: boolean;
    /** True if the `pubkey` can be loaded as a read-write account. */
    isWritable: boolean;
  };
```

Thus the user could provide `accounts.anchorRemainingAccounts` that way.

This would need to be added to each anchor instruction as sort of a _hidden_ feature in case it is needed.

Please LMK if this is in a form that would solve your issue.

Thanks.

**Comment by 0xPratik** [comment]
Ya that's what it's needed thanks @thlorenz for working on it. I personally think that instead of `anchorRemainingAccounts` it can just be `remainingAccounts`

**Comment by thlorenz** [comment]
>  instead of anchorRemainingAccounts it can just be remainingAccounts

I know the name is verbose, but it's designed to avoid name clashes with named accounts :)
Prefixing with `anchor` is still better than doing something like `__remainingAccounts` IMHO .. what do you think?

**Comment by 0xPratik** [comment]
Ya better it be clear then clashing with something else

**Comment by thlorenz** [comment]
Should be fixed now went out as `@metaplex-foundation/mpl-auction-house@2.3.0`
