### ISSUE TITLE
[Bug]: panicked at 'index out of bounds: the len is 0 but the index is 0', src/processor/mint.rs:494:40

### ISSUE THREAD

**Issue by stanleycyang** [metaplex-foundation/metaplex-program-library#709]
### Which package is this bug report for?

candy-machine

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

Minting from a candy machine started breaking with the recent release, mints were working fine before. 

Here is a failed transaction: https://solscan.io/tx/2fAVPWkArqd2YYZ5rBoBHqWGdz7hXJkBXyc1Wi5iuPPkY766eDY3MVU3gLcwAJuwjnktsG85QW32x2VGpr87VgCk

Every time a mint happens, it throws this error: `https://solscan.io/tx/2fAVPWkArqd2YYZ5rBoBHqWGdz7hXJkBXyc1Wi5iuPPkY766eDY3MVU3gLcwAJuwjnktsG85QW32x2VGpr87VgCk`

### Priority this issue should have

High (immediate attention needed)

**Comment by febo** [comment]
@stanleycyang Can you confirm if you are still experiencing this issue?
