### ISSUE TITLE
[Bug]: Can't full-burn verified NFT because its collection metadata account is closed/null

### ISSUE THREAD

**Issue by dkaladsf** [metaplex-foundation/metaplex-program-library#712]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

I'm trying to burn a set of NFTs that are verified tokens of a collection (links to relevant account/s below). For some reason, the collection metadata has already been closed, so there is no way of full-burning these NFTs besides spl-token burn.

From what I've seen, it's failing because of this line since `is_correct_account_type` in `from_account_info` codeblock assumes that the data passed down to it is non-null: https://github.com/metaplex-foundation/metaplex-program-library/blob/fedbdeab91074863de1d53c186c46e99158660cd/token-metadata/program/src/processor.rs#L1819 

Would it be possible to have an additional constraint that would allow users to full burn verified NFTs with empty/closed collection metadata accounts? My suggestion would be to allow empty collection metadata account field for verified NFTs iff the account is indeed empty already.

Example of NFT in question: 
Mint - https://solscan.io/token/9PEFoHk1b4fWPmkrxGEtwxKoWwzCjvgcdCAKaEJj1FgS
Closed Collection Metadata Account (PDA) - https://solscan.io/account/Haib8xBrcBCDdoKZUARZuqTL5n6ssjghaZESgekXbPUk

### Relevant log outputs

[What is returned if I don't provider collection metadata account:](https://solscan.io/tx/2EZ3THgWRaLRzBQuV81x5jqubSZH7odfcHhsp76HgdP6Ce4mVjHTsa2Vc1wHsAjVnDurxM79pbJFHbcpJopu6Tui)
```shell
#1 Metaplex Token Metadata instruction
> Program log: Instruction: Burn NFT
> Program log: Can't burn a verified member of a collection w/o providing collection metadata account
> Program Metaplex Token Metadata  consumed 5290 of 200000 compute units
> Program returned error: custom program error: 0x67
```
[What is returned if I provide the correct, empty collection metadata account:](https://solscan.io/tx/e2m6fiMEvRGRNEJdUrH5EpnAmgZd9GC89dtP42cnoBbvCthN5X3j9Rgv2wd4JWe4pKNvgNwUquZadUFkmjxkKtG)
```shell
#1 Metaplex Token Metadata instruction
> Program log: Instruction: Burn NFT
> Invoking Token Program
  > Program log: Instruction: Burn
  > Program Token Program  consumed 4836 of 186048 compute units
  > Program returned success
> Invoking Token Program
  > Program log: Instruction: CloseAccount
  > Program Token Program  consumed 2916 of 178489 compute units
  > Program returned success
> Program log: panicked at 'index out of bounds: the len is 0 but the index is 0', program/src/utils.rs:857:6
> Program Metaplex Token Metadata  consumed 26958 of 200000 compute units
> Program returned error: BPF program panicked
```

### Priority this issue should have

Low (slightly annoying)

**Comment by samuelvanderwaal** [comment]
This is fixed in v1.6.5 but is not deployed to devnet or mainnet just yet.
