### ISSUE TITLE
[Bug]: Edition #70 was minted for a master edition with max supply #69

### ISSUE THREAD

**Issue by arcticmatt** [metaplex-foundation/metaplex-program-library#776]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

For https://formfunction.xyz/@degenpoet/F5smPCKim7iDQQGL3kGA2mtJDaA5wd2E18Vqa5nbJbHD?width=3000&height=4000, you can see that edition #70 was successfully minted, even though the max supply is 69

- Master edition https://explorer.solana.com/address/F5smPCKim7iDQQGL3kGA2mtJDaA5wd2E18Vqa5nbJbHD?cluster=mainnet-beta. You can see that the max supply is 69
- Edition #70 https://explorer.solana.com/address/dDgJjQDcTxeRmiyda7zn4xNTzS6YD1wowt8rhDLVRuu?cluster=mainnet-beta 

AFAICT it's a bug with this code https://github.com/metaplex-foundation/metaplex-program-library/blame/master/token-metadata/program/src/utils.rs#L554-L572

Let's say `max_supply = 69` and `current_supply = 69`

Then, `new_supply = 69`, which is not `> max`, and so `MaxEditionsMintedAlready` will never be hit

### Priority this issue should have

High (immediate attention needed)

**Comment by roederw** [comment]
Resolved. Thank you for bringing this to our attention. Follow up here if the issue seems to NOT be resolved!

**Comment by arcticmatt** [comment]
@roederw thanks! Do you mind linking to the PR/commit that fixed this?

**Comment by samuelvanderwaal** [comment]
> @roederw thanks! Do you mind linking to the PR/commit that fixed this?

https://github.com/metaplex-foundation/metaplex-program-library/pull/779
