### ISSUE TITLE
Aucitioneer program doesn't exist on Mainnet [Bug]: 

### ISSUE THREAD

**Issue by salman-kryptomind** [metaplex-foundation/metaplex-program-library#777]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

hi there! I'm trying to find Auctioneer contract but I can't it on the explorer.
Here the program id I'm looking for : neer8g6yJq2mQM6KbnViEDAD4gr3gRZyMMf4F2p3MEh

Let me know If I am missing something.

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
It's not on mainnet yet.

**Comment by samuelvanderwaal** [comment]
[It is now.](https://explorer.solana.com/address/neer8g6yJq2mQM6KbnViEDAD4gr3gRZyMMf4F2p3MEh)
