### ISSUE TITLE
Problem while freezing nft account in Rust

### ISSUE THREAD

**Issue by bamdadam** [metaplex-foundation/metaplex-program-library#789]
Hello i've been trying to write a staking program and i need to freeze an nft. i delegate it to a pda before trying to freeze it 
![image](https://user-images.githubusercontent.com/78018383/193890245-5fbb30b5-227e-4081-832e-183fa4aa3f65.png)
my stake context: 
![image](https://user-images.githubusercontent.com/78018383/193890474-6b87188f-42ab-410f-b46a-bdd346c41ddf.png)
delegate context:
![image](https://user-images.githubusercontent.com/78018383/193890566-19ba02df-2dbd-4c0e-8505-33863d6c78b7.png)
making freeze instruction:
![image](https://user-images.githubusercontent.com/78018383/193890739-ac32e73e-52f7-4c10-8300-8de861b21928.png)
and invoking it: 
![image](https://user-images.githubusercontent.com/78018383/193890819-8f8a4f2a-cd4e-4057-a8f0-22aa3e1f23f3.png)
i've tried numerous ways and checked cardinals and candy machines freeze_delegated_nft but whatever i do i keep getting:
![image](https://user-images.githubusercontent.com/78018383/193891024-2c4a306b-8722-47e2-bb22-2a8f2836c483.png)
can anyone tell me what im doing wrong?
Thanks in advance.

**Comment by samuelvanderwaal** [comment]
> Hello i've been trying to write a staking program and i need to freeze an nft. i delegate it to a pda before trying to freeze it ![image](https://user-images.githubusercontent.com/78018383/193890245-5fbb30b5-227e-4081-832e-183fa4aa3f65.png) my stake context: ![image](https://user-images.githubusercontent.com/78018383/193890474-6b87188f-42ab-410f-b46a-bdd346c41ddf.png) delegate context: ![image](https://user-images.githubusercontent.com/78018383/193890566-19ba02df-2dbd-4c0e-8505-33863d6c78b7.png) making freeze instruction: ![image](https://user-images.githubusercontent.com/78018383/193890739-ac32e73e-52f7-4c10-8300-8de861b21928.png) and invoking it: ![image](https://user-images.githubusercontent.com/78018383/193890819-8f8a4f2a-cd4e-4057-a8f0-22aa3e1f23f3.png) i've tried numerous ways and checked cardinals and candy machines freeze_delegated_nft but whatever i do i keep getting: ![image](https://user-images.githubusercontent.com/78018383/193891024-2c4a306b-8722-47e2-bb22-2a8f2836c483.png) can anyone tell me what im doing wrong? Thanks in advance.

Why is the spl_program account commented out in the `account_infos` slice? Uncomment that and it should work.

**Comment by bamdadam** [comment]
hey
sorry for the late reply, so i did as you suggested and it didn't work.
![image](https://user-images.githubusercontent.com/78018383/194324100-cbe58cb3-ab23-4ca1-a6f8-6fe2a8be75f6.png)
got the same error message as before 
![image](https://user-images.githubusercontent.com/78018383/194324260-a29a6318-2dab-4d6e-9d47-4f6655d00b3e.png)

**Comment by bamdadam** [comment]
@samuelvanderwaal 
hey , can you check this out again whenever you have time?

**Comment by bamdadam** [comment]
@metaplex-foundation 
can anyone take a look at this?
