### ISSUE TITLE
Big issue !!!!

### ISSUE THREAD

**Issue by Tusardutta** [metaplex-foundation/metaplex-program-library#798]
Creating token TDz4nVhhKijbFjUSQnpxet9WAtR89bcGfmbTPTYeMCi
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0 [3 log messages]

**Comment by Tusardutta** [comment]
Please help me

**Comment by samuelvanderwaal** [comment]
Please ask for help with this kind of issue on the Metaplex Discord. You haven't provided enough information to understand what the issue is.
