### ISSUE TITLE
MetaplexError: AuctionHouse > Auctioneer Authority Required[Bug]: 

### ISSUE THREAD

**Issue by samia-invozone** [metaplex-foundation/metaplex-program-library#803]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

JS SDK

### Issue description

After running the delegate instructions of the Auctioneer Program, My previous code for fetching the AH details is no more working. It says Auctioneer Authority is also required but when I pass the authority parameter it gives an error. Below is the code for fetching auction house details:
`const auctionHouse = await metaplex
      .auctions()
      .findAuctionHouseByAddress(
        new PublicKey("4e46fum9qnc7GQqShBiSrCLMLA3jEyo4kABNe6SsQSvP"),
        new PublicKey("BGGcNtvj1bBCqsrGcHjvtpAGHnoRp4bhC7EUqYFXufVJ")
      )
      .run();`

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'reduce')
    at toAuctionHouse (AuctionHouse.ts:113:1)
    at Object.handle (findAuctionHouseByAddress.ts:86:1)
    at async Task.ts:82:1
    at async Disposable.run (Disposable.ts:34:1)
    at async auctionHouseDetails (ListNFT.tsx:37:1)
```

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
@samia-invozone can you open this issue on the [JS SDK repo](https://github.com/metaplex-foundation/js) instead of here? Thanks!
