### ISSUE TITLE
[Bug]: Execute sale - sum of account balances before and after instruction do not match

### ISSUE THREAD

**Issue by viyer28** [metaplex-foundation/metaplex-program-library#822]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

Running into a weird error with **executeSale** - I'm trying to execute a sale as the seller of a token on an existing buy offer.
Basically, I'm packing **createSellOffer**, **printListingReceipt**, **executeSale**, and **printPurchaseReceipt** in one transaction.
In the **executeSale** instruction, I get this error:
 
`sum of account balances before and after instruction do not match`

It looks like something to do with ImmutableOwner and Token Program 2022. I've attached a sample failed devnet transaction [here](https://explorer.solana.com/tx/2Tnh1L9DSDCBAFsKiTT1Q3VYb9SdzjFiLProfGqafNrLXABxjK24bhD1NgRf99YnHMdcSitean1VSmyoTCYSu4k8?cluster=devnet).

Any idea what could be going on?

### Relevant log output

```shell
> Program log: Instruction: ExecuteSale
> Invoking System Program
  > Program returned success
> Invoking System Program
  > Program returned success
> Invoking System Program
  > Program returned success
> Invoking System Program
  > Program returned success
> Invoking Associated Token Account Program
  > Program log: Create
  > Invoking Token Program
    > Program log: Instruction: GetAccountDataSize
    > Program Token Program  consumed 1622 of 637426 compute units
    > Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=
    > Program returned success
  > Invoking System Program
    > Program returned success
  > Program log: Initialize the associated token account
  > Invoking Token Program
    > Program log: Instruction: InitializeImmutableOwner
    > Program log: Please upgrade to SPL Token 2022 for immutable owner support
    > Program Token Program  consumed 1405 of 630936 compute units
    > Program returned success
  > Invoking Token Program
    > Program log: Instruction: InitializeAccount3
    > Program Token Program  consumed 4241 of 627052 compute units
    > Program returned success
  > Program Associated Token Account Program  consumed 23545 of 646018 compute units
  > Program returned success
> Invoking Token Program
  > Program log: Instruction: Transfer
  > Program Token Program  consumed 4735 of 613710 compute units
  > Program returned success
> Program Auction House  consumed 104003 of 709593 compute units
> Program returned error: sum of account balances before and after instruction do not match
```

### Priority this issue should have

High (immediate attention needed)

**Comment by gabspeck** [comment]
Hi, I have encountered this issue as well. Someone on the Discord channel suggested that this is due to some bug in executing sales using the seller's key. 

The workaround suggested, and that worked for me, was enabling `requireSignOff` in the auction house instance and then adding the auction house's authority as a signer to the instruction. This may or may not be viable to you, since requireSignOff will require all of the AH transactions to be signed by your auction house authority.

**Comment by AmmarKhalid123** [comment]
@gabspeck  what should one do if turning `requireSignOff` on is not viable in my use case, bcs I can't really do that

**Comment by boredjoker** [comment]
any update?

**Comment by AmmarKhalid123** [comment]
@austbot @blockiosaurus any suggestions on this?

**Comment by crypt0miester** [comment]
double check that the fee payer has more than needed to execute the txn. since there are a couple of accounts created when using the route you guys have gone through. 

would also be helpful to include a txn id on devnet.

**Comment by AmmarKhalid123** [comment]
In the escrow? bcs in escrow we have to enter the exact amount while creating the instruction using metaplex-foundation
And if you're talking about seller's wallet (which is executing the transaction and will be the fee payer of all txs in this case), they already have around 0.1 sol extra in their wallet which ig should be enough

Also, if it might help, executeSale works fine when the flow is: Seller lists

**Comment by crypt0miester** [comment]
`Also, if it might help, executeSale works fine when the flow is: Seller lists for x sol (sell, sellListingReceipt) and then buyer comes and buy (bid, bidReceipt, executeSale, executeSaleReceipt)`

sounds like the intended right flow, when requireSignOff is false. 

two things you can also try:
 - with a seller (owner of the nft) whom is not one of the metadata creators.
 - separate accepting the offer txn from the execute sale txn.

see if that works for you.

**Comment by AmmarKhalid123** [comment]
Have tried both of them, doesnt work

**Comment by viyer28** [comment]
@crypt0miester I've tried manually adding funds to the sellerTradeState too, since the seller is the payer in this case. that also didn't seem to work.

what's strange to me is this exact flow was working normally around a month ago, it was a recent version of auction house that caused it to break

**Comment by crypt0miester** [comment]
> @crypt0miester I've tried manually adding funds to the sellerTradeState too, since the seller is the payer in this case. that also didn't seem to work.
> 
> what's strange to me is this exact flow was working normally around a month ago, it was a recent version of auction house that caused it to break

ez pz. find the working contract and deploy it. good luck.

**Comment by AmmarKhalid123** [comment]
> ez pz. find the working contract and deploy it. good luck.
I traversed the commits which updated the AH, and this last commit on Auction House, i.e.,
https://github.com/metaplex-foundation/metaplex-program-library/tree/380266975aafeb00f25016e119f881d9c3f437e3/auction-house
The tests for execute_sale are failing in this commit, before that its working. So I'm guessing this one must be creating some issue
@crypt0miester

**Comment by AmmarKhalid123** [comment]
@crypt0miester 
deployment on devnet took around 17-18ish sol, which would be a bit too costly on mainnet :(
Any chance this issue will be fixed in near future?

**Comment by crypt0miester** [comment]
> @crypt0miester 
> deployment on devnet took around 17-18ish sol, which would be a bit too costly on mainnet :(
> Any chance this issue will be fixed in near future?

prune auctioneer functions off. I have no idea what will happen in the future. kek

I'm just trying to help you guys.

**Comment by crypt0miester** [comment]
> Thank you @crypt0miester, it worked. @blockiosaurus @austbot @levicook This is a verified bug. Reverting code to [90faa34](https://github.com/metaplex-foundation/metaplex-program-library/commit/90faa3459b596021b1d734bffedd83893256a981), deploying the contract, and then using that programId resolves the issue. This should be a high priority task, as in solscan I cannot see any successful executeSale executed by a seller too, so it must be affecting alot of people out there. I don't have much knowledge of rust else I would've looked into it to resolve the issue

the commit you linked only has bubblegum changes. weird.

deploy the idl and apr. iirc, explorer.solana.com checks for idl data.

**Comment by AmmarKhalid123** [comment]
@crypt0miester 
Umm, I guess we should look for the commits that came after 90faa3459b596021b1d734bffedd83893256a981 (29 Sept) since the flow is working fine on this commit, and below is the list of commits that made some changes to auction-house programs and occurred after the mentioned commit

f448a128c0db027501e5c5097f1d46e28cf88757 (updates execute_sale/mod.rs)
03ad5bd083f930f4828276317c8085515efc2d14 (doesn't update AH programs, just the js files)
471d3792b755ffe76e0425b41f25b9c3f70cd182 (updates utils.rs)
ac347fb4c5dec6e32f3e62ff3a87cdfa016fb378 (doesnt update programs, just the js sdk)
40c0df078ca14b5240897b4c4259d31050ba6acd (update execute_sale/mod.rs)
bcc37d6c51bd1adeb889212bcc750df9fdedfab3 (doesnt update programs, just the sdk)
380266975aafeb00f25016e119f881d9c3f437e3 (this is the latest commit, and the tests for execute_sale are failing here)

That's the only thing I could think of which might help to whoever comes across this and have anchor/rust knowledge. The changes in any one of the above is breaking the flow

**Comment by AmmarKhalid123** [comment]
> perhaps moving it back to line 1791 inside the check would make it work. no idea of the implications though. so make sure the rust tests go through.

Makes sense. Currently occupied with few things, can try this out in a day or two. Will update here if the solution works

**Comment by blockiosaurus** [comment]
Thanks for catching this and pinning it down to a commit! It looks like we're aware of this bug but it got lost in the pre-Breakpoint shuffle. I'm on vacation this week so will ping the on-call engineer again to make sure they follow up.

**Comment by samuelvanderwaal** [comment]
Hi all, apologies for the delay in addressing this. I'm struggling to duplicate this error in Rust BPF tests. Here's what I'm doing, please advise if this isn't properly duplicating the flow that is causing the error:

* Create a public bid with a price of `500_732_504` by calling `public_buy` and `print_bid_receipt` in the same transaction
* Build a transaction with the following instructions:
   - sell
   - print_listing_receipt
   - execute_sale
   - print_purchase_receipt
   
   using the same price of `500_732_504` on the token mint used in the public bid. Execute this transaction.
   
   This succeeds. You can see the [Rust test here](https://github.com/metaplex-foundation/metaplex-program-library/pull/868/files).

**Comment by AmmarKhalid123** [comment]
@samuelvanderwaal try `buy` and `bid_receipt`, not the `public_buy` and `public_bid_receipt`

**Comment by AmmarKhalid123** [comment]
just tried, using `public_buy` with this flow also throwing same error :/

**Comment by samuelvanderwaal** [comment]
> just tried, using `public_buy` with this flow also throwing same error :/

Both `buy` and `public_buy` work with my Rust BPF tests so I'm not duplicating your flow somehow. I'll try setting up a test with a CLI on devnet tomorrow so we can compare transactions. Thanks for your patience.

**Comment by viyer28** [comment]
> [40c0df0](https://github.com/metaplex-foundation/metaplex-program-library/commit/40c0df078ca14b5240897b4c4259d31050ba6acd) (update execute_sale/mod.rs)

My hunch is it has something to do with this commit.

**Comment by AmmarKhalid123** [comment]
@crypt0miester @viyer28, thanks for the suggestions. I tried to make the changes as suggested by you two, and deployed on devnet (ProgramId: 3D9cn2367JxcHyKPQpySFoZgf2ZDekh9ZVfEreVWT4WA). Tested with the same flow which was causing the issue on ExecuteSale for @viyer28 and me too, but is working fine. Just in case any of you wants to test it, below is the auction house keys which I created using this ProgramId and tested the flow on.
{
    "authority": "rHETQthTcwEVwHCxj3YDGQcJCyFxCAn5QQmbgnMjYzq",
    "payer": "rHETQthTcwEVwHCxj3YDGQcJCyFxCAn5QQmbgnMjYzq",
    "treasuryMint": "So11111111111111111111111111111111111111112",
    "feeWithdrawalDestination": "rHETQthTcwEVwHCxj3YDGQcJCyFxCAn5QQmbgnMjYzq",
    "treasuryWithdrawalDestination": "rHETQthTcwEVwHCxj3YDGQcJCyFxCAn5QQmbgnMjYzq",
    "treasuryWithdrawalDestinationOwner": "rHETQthTcwEVwHCxj3YDGQcJCyFxCAn5QQmbgnMjYzq",
    "auctionHouse": "21aSox4W7C72XVdeyfnecgJ4xS8TmUXbU3P1UxEQL4uS",
    "auctionHouseFeeAccount": "5GZRUuX6sds78ntTyBmf4mrQAqNQANsgmGruGbHwWBvu",
    "auctionHouseTreasury": "3dtumsMMWHDWzuVdzbuQnFcQ5PFFLMw9HHZ1Z1LUugrH"
}

**Comment by AmmarKhalid123** [comment]
@samuelvanderwaal can you take a look at this PR #871

**Comment by crypt0miester** [comment]
> @samuelvanderwaal can you take a look at this PR #871 

glad you got it working mate.

**Comment by AmmarKhalid123** [comment]
@crypt0miester wouldn't have been possible without your help though. Let's hope it gets approved.

**Comment by samuelvanderwaal** [comment]
@AmmarKhalid123 I've deployed a fix to devnet. Please let me know if this resolves the issue for you.

**Comment by AmmarKhalid123** [comment]
@samuelvanderwaal yes it does, working on devnet now. Thank you. Can you deploy the fix to mainnet too.

**Comment by samuelvanderwaal** [comment]
> @samuelvanderwaal yes it does, working on devnet now. Thank you. Can you deploy the fix to mainnet too?

The fix is on mainnet now. Please let us know if you see any more issues with this.
