### ISSUE TITLE
[Bug]: No deprecation notice for null freeze authority in commit 33808b7

### ISSUE THREAD

**Issue by Flawm** [metaplex-foundation/metaplex-program-library#859]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

I believe 33808b73079eda8bdaee7c67bf9d8f9b9eefd514 is too aggressive, there wasn't a deprecation notice or anything of the likes and instead is turned into an error. I have production systems that would have gone down had I not randomly found this and had time to fix it, and I'm just one dude in my basement. What's the reasoning behind this change? Are NFTs that historically have null mint / freeze addresses no longer considered 'valid' metaplex nfts?

This reminds me of the roll out last year that changed the creators vec & seller fee basis points to be immutable, but was rolled back, is there a change log or some kind of release schedule that people can follow? How are we supposed to know when things like this change, other than when users call us at 4 am about their mints not working? :sweat_smile: 

### Relevant log output

```shell
> Program logged: "Cannot create NFT with no Freeze Authority."
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
Hey this is a valid concern but a couple things to note:

* We've spent a lot of effort to keep things backwards compatible but sometimes we have to move fast to address market or security needs
* This is in preparation for royalty enforcement which is something demanded by the community and which people want a solution for quickly
* Make sure you're following our [Metaplex Status](https://twitter.com/MetaplexStatus) account on Twitter for latest updates
* This change is only on devnet at the moment; but will be [going to mainnet soon](https://twitter.com/MetaplexStatus/status/1585635707024211968)

Sorry this change broke your code and we're working hard to keep breaking changes to a minimum.

**Comment by samuelvanderwaal** [comment]
> Are NFTs that historically have null mint / freeze addresses no longer considered 'valid' metaplex nfts?

They are still valid Metaplex NFTs.
