### ISSUE TITLE
Tackoman73 

### ISSUE THREAD

**Issue by tackoman** [metaplex-foundation/metaplex-program-library#900]
https://github.com/tackoman/metaplex-program-library/blob/master/.github/actions/build-token-metadata/action.yml

**Comment by tackoman** [comment]
> https://github.com/tackoman/metaplex-program-library/blob/master/.github/actions/build-token-metadata/action.yml

**Comment by samuelvanderwaal** [comment]
This issue needs a description and details or it will be closed.
