### ISSUE TITLE
Bump mpl-token-metadata dependencies

### ISSUE THREAD

**Issue by fedorerd** [metaplex-foundation/metaplex-program-library#920]
`mpl-token-metadata crate @ 1.6.4` refers to some old dependencies. Including solana 1.10 and spl-associated-token-account 1.0.5. 

Personally, I faced compatibility issues due to new Anchor lang release (Anchor required spl associated token account 1.1, which conflicted with mpl-token-metadata 1.0.5), but I believe, there are much more possible issues.

**Comment by samuelvanderwaal** [comment]
Yeah it's on our agenda to bump up to the newest Anchor and Solana versions, it's a bit of an effort tho so not sure exactly when it's going to happen. Anchor 0.26 has only been out a week or so.

**Comment by dr497** [comment]
Do you have more clarity on when the dependencies will be updated?

**Comment by fedorerdFT** [comment]
Resolved in `mpl-token-metadata = "1.7.0"`!

**Comment by fedorerd** [comment]
Resolved in `v1.7.0`!
