### ISSUE TITLE
Please add mpl-token-metadata crate to crate.io registry

### ISSUE THREAD

**Issue by nibbus0x** [metaplex-foundation/metaplex-program-library#97]
I am unable to add the  [`mpl-token-metadata`](https://metaplex-foundation.github.io/metaplex-program-library/mpl_token_metadata/index.html) crate my application using `cargo add`. 

I think the crate needs to be added to the crates.io registry

**Comment by nibbus0x** [comment]
Is there a different registry I can use it from?

**Comment by ozgrakkurt** [comment]
you can use it like:
```
[dependencies]
mpl-token-metadata = { git = "https://github.com/metaplex-foundation/metaplex-program-library" }
```
in your Cargo.toml for now.
It is working for us except `utilize` instruction

**Comment by nibbus0x** [comment]
@ozgrakkurt Thank you, that worked!
